config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  root 'welcome#index'
  get 'welcome/index'
  resources :sessions
  resources :companies
  resources :posts do
    resources :comments
  end
  resources :users

  namespace :admin do
    resources :users
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  
end

app/models/company.rb
class Company < ApplicationRecord
  has_secure_password
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  paginates_per 3
  has_many :comments, dependent: :destroy
  validates :post, presence: true
  validates :ranking, presence: true
  validates :company_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :fullname, presence: true
  validates :telephone, presence: true
  validates :email, presence: true, uniqueness: true, length: {maximum: 200},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :set_user!, only: [:show, :edit, :update]
    def index
        @users = User.all.order('id ASC')
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
        redirect_to admin_users_path, notice: 'user created successfully'
        else
            render.new
        end
    end


    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
 before_action :find_comment, only: [:destroy, :edit , :update]
def create
@comment = @post.comments.create(params[:comment].permit(:content))
@comment.save
if @comment.save
  redirect_to post_path(@post)
else
  render 'new'
end
end

def destroy
@comment.destroy
redirect_to post_path(@post)
end

def edit

end

def update
if @comment.update(params[:comment].permit(:content))
  redirect_to post_path(@post)
  else
    render 'edit'
  end
end



private
def find_post

  @post = Post.find(params[:post_id])
end

def find_comment
  @comment = @post.comments.find(params[:id])
end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

 
  def index
    @companies = Company.all
  end

  
  def show
  end 
  
  def new
    @company = Company.new
  end

  
  def edit
  end

  def create
    @company = Company.new(company_params)

    
      if @company.save
        redirect_to @company, notice: 'Company was successfully created.' 
        
        
      else
        render :new 
        
     
    end
  end


  def update
    
      if @company.update(company_params)
       redirect_to @company, notice: 'Company was successfully updated.' 
        
      else
        render :edit 
        
      
    end
  end

 
  def destroy
    @company.destroy
    
      redirect_to companies_url, notice: 'Company was successfully destroyed.' 
  end

  private
    
    def set_company
      @company = Company.find(params[:id])
    end

   
    def company_params
      params.require(:company).permit(:company_name, :email, :password, :password_confirmation)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def index
    @posts = Post.all.page(params[:page])
  end


  def show
    @comments = Comment.where(post_id: @post)
  end


  def new
    @post = Post.new
  end


  def edit
  end


  def create
    @post = Post.new(post_params)


      if @post.save
        redirect_to posts_path, notice: 'Post was successfully created.'
      else
       render :new


    end
  end


  def update

      if @post.update(post_params)
         redirect_to posts_path, notice: 'Post was successfully updated.' 

      else
        render :edit


    end
  end


  def destroy
    @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:company_name, :post, :user_id, :ranking)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id

      redirect_to posts_path(user.id)
    else
      flash.now[:danger] = 'Login failed'
      render 'new'
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'You logged out'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

 
  def index
    @users = User.all
  end

  def show
  end

  
  def new
    @user = User.new
  end

  
  def edit
  end

  
  def create
    @user = User.new(user_params)

    
      if @user.save
        session[:user_id] = @user.id
        redirect_to posts_path, notice: 'User was successfully created.' 
        
      else
        render :new 
        
    end
  end

 
  def update
    
      if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.' 
        
      else
        render :edit 
        
      
    end
  end

  
  def destroy
    @user.destroy
    
     redirect_to users_url, notice: 'User was successfully destroyed.' 
     
    
  end

  private
    
    def set_user
      @user = User.find(params[:id])
    end

    
    def user_params
      params.require(:user).permit(:fullname, :email, :telephone, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/index.html.erb
<h3>User list</h3>
<table class="table">
  <thead>
    <tr>
      <th>Names</th>
      <th>Email</th>
      <th>Phone</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.fullname %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.telephone %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/_comment.html.erb
<ul>
  <% @comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <p><br><%= comment.content %><br>

        <%= link_to "delete", [comment.post, comment], method: :delete%>
        <%= link_to "edit ", edit_post_comment_path(comment.post, comment)%></p>
        </li>
    
    <% end %>
  <% end %>
<%= render 'comments/form'%>
</ul>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>

<%= f.text_area :content, class:"single-input", placeholder:"enter comment"%>
<%= f.submit "post comment", class:"genric-btn info-border circle" %>
<%end%>

app/views/comments/create.html.erb
<h1>Comments#create</h1>

app/views/comments/edit.html.erb
<%= form_for ([@post, @comment]) do |f| %>

    <%= f.text_area :content%>
    <%= f.submit "post comment" %>

      <%end%>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.company_name %></td>
        <td><%= company.email %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @company.company_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineServicesEvaluationPlatform</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#357376;">
  <a class="navbar-brand" href="#" id="navbar-brand">OnlineServicesEvaluationPlatform</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav  mr-auto">
      <% if logged_in? %>
      <li class="nav-item">
      <%= link_to 'My Posts', posts_path, class:"nav-link", id:"navitem" %>
      </li>
      <li class="nav-item">
      <%= link_to 'New Post', new_post_path, class:"nav-link", id:"navitem" %>
      </li>
      
      <li class="nav-item " >
        <%= link_to "Logout", session_path(current_user.id), method: :delete, class:"nav-link", style:"color:white;" %>
      </li>
      <% else %>
      <li class="nav-item active">
        <%= link_to 'Home', welcome_index_path, class:"nav-link", id:"navitem" %>
      </li>
    </ul>
    <span class="form-inline">
      <%= link_to 'Login', new_session_path, class:"btn btn-success btn-sm rounded-pill" %>
    </span>
  <% end %>

  </div>
  </nav><br>


<% if logged_in? %>

<i style="color:black">ようこそ <%=current_user.fullname %> </i>
<%end%>



    <%= yield %><br><br><br><br>
    <!-- Footer -->
    <footer class="page-footer font-small cyan darken-3" style="background-color:#357376;">
      <center>
      <!-- Footer Elements -->
      <div class="container">

        <!-- Grid row-->
        <div class="row">

          <!-- Grid column -->
          <div class="col-md-12 py-5">
            <div class="mb-5 flex-center">

              <!-- Facebook -->
              <a class="fb-ic" style="color:#fff;">
                <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!-- Twitter -->
              <a class="tw-ic" style="color:#fff;">
                <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!-- Google +-->
              <a class="gplus-ic" style="color:#fff;">
                <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!--Linkedin -->
              <a class="li-ic" style="color:#fff;">
                <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!--Instagram-->
              <a class="ins-ic" style="color:#fff;">
                <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
              </a>
              <!--Pinterest-->
              <a class="pin-ic" style="color:#fff;">
                <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
              </a>
            </div>
          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row-->

      </div>
      <!-- Footer Elements -->
      </center>
      <!-- Copyright -->
      <div class="footer-copyright text-center py-3" style="color:#fff;">© 2019 Copyright:
        Online Services Evaluation Platform
      </div>
      <!-- Copyright -->

    </footer>
    <!-- Footer -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="w-25 border rounded shadow p-4 m-auto">
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.text_field :company_name, class:"form-control", placeholder:"Enter Company Name" %>
    </div>
    <div class="form-group">
      <%= form.text_area :post, class:"form-control", placeholder:"Enter Your Post", row:"3" %>
    </div>
    <div class="form-group">
      <%= form.label :ranking %><br />
      <%= form.radio_button :ranking, 'Fair' %> Fair<br />
      <%= form.radio_button :ranking, 'Good' %> Good<br />
      <%= form.radio_button :ranking, 'Very Good' %> Very Good<br />
      <%= form.radio_button :ranking, 'Excellent' %> Excellent<br />
    </div>
    <div class="field">
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="actions">
      <%= form.submit "Save", class:"form-control w-25 btn-success m-auto" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1 class="text-center">Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<center>
<div class="card w-75">
<div class="card-header" style="background-color:#357376;">


<h1 style="color:#fff;">Posts</h1>
</div>
<div class="card-body">

<table class="table">
  <thead>
    <tr>
    <th>UserName</th>
      <th>Company name</th>
      <th>Post</th>
      <th>Ranking</th>
      <th>Feedback</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
      <td><%= post.user.fullname%></td>
        <td><%= post.company_name %></td>
        <td><%= post.post %></td>
        <td>
          <% if post.ranking == "Excellent" %>
            <p class="btn btn-success btn-sm">Excellent</p>
          <% end %>
          <% if post.ranking == "Very Good" %>
            <p class="btn btn-info btn-sm">Very Good</p>
          <% end %>
          <% if post.ranking == "Good" %>
            <p class="btn btn-warning btn-sm">Good</p>
          <% end %>
          <% if post.ranking == "Fair" %>
            <p class="btn btn-danger btn-sm">Fail</p>
          <% end %>
        </td>

        <td><% if  post.comments.present? %><% post.comments.each do |comment| %>
          <%= comment.content %>
          <% end %>
          <% else %>
            Please-wait
          <% end %>
          </td>
        <% if logged_in? %>
        <% if current_user.id == post.user_id || current_user.admin == true%>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @posts%>
<br>
</div>
</div>

</center>

app/views/posts/new.html.erb
<h1 class="text-center">New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<center>
<div class="card w-50">
<div class="card-header" style="background-color:#357376;">


<h1 style="color:#fff;">Post details</h1>
</div>
<div class="card-body">
<p>
  <strong>Company name:</strong>
  <%= @post.company_name %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post.post %>
</p>
<p>
  <strong>Ranking:</strong>
  <%= @post.ranking %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>
<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-info btn-sm" %>
</div>

</div>

</center>


<% if current_user.admin?%>
  <%= render 'comments/comment' %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container register">
  <div class="row">
    <div class="col-md-3 register-left">
      <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
      <h3>Welcome</h3>
      <p>Welcome Please Login Here If You Have An Account!</p>
      <%= link_to "Login", new_session_path, class:"nav-link", id:"loginbtn", style:"color:#fff;" %><br/>
    </div>
    <div class="col-md-9 register-right">
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
          <h3 class="register-heading">New User</h3>
        <div class="row register-form">
          <div class="col-md-6">
            <div class="form-group">
              <%= form.text_field :fullname, class:"form-control", placeholder:"Full Name *" %>
            </div>
            <div class="form-group">
              <%= form.email_field :email, class:"form-control", placeholder:"Email *" %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= form.text_field :telephone, class:"form-control", placeholder:"Telephone Number *" %>            
            </div>
            <div class="form-group">
              <%= form.password_field :password, class:"form-control", placeholder:"Password *" %>
            </div>    
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Password Confirmation *" %>
            </div>
            <%= form.submit class:"btnRegister" %>
    </div> 
    </div>
    </div>
    </div>
    </div>
  </div>           
</div><br><br>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Email</th>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fullname %></td>
        <td><%= user.email %></td>
        <td><%= user.telephone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> 

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @user.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @user.telephone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<!doctype html>
<html>
<head>
<title>Project</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<center>
<div class="card" id="slideshow">
<div class="card-body">
<h1 class="heading">Welcome To Online Services Evaluation Platform</h1>

<p class="paragraphy">If Is Not The Employers Who Pays The Wages.<br>Employers Only Handle The Money.<br>It Is The Customer Who Pays The Wages <br>
 Help Us Evaluate The Service We Provide You By Choosing User Or Company If You Are An Admin </p>

</div><br>
</center>
<div class="container">
<div class="row">
<div class="col-md-12">
<div class="card-group">
  <div class="card">
    <%= image_tag('about.jpeg', class:"card-img-top", style:"height:10rem;") %>
    <div class="card-body">
      <h5 class="card-title">About Us</h5>
      <p class="card-text">This is an online App help the company to evaluate their service by allowing the customes to express their feeling on the company.</p>
    </div>
  </div>
  <div class="card">
    <%= image_tag('openservice.png', class:"card-img-top", style:"height:10rem;") %>
    <div class="card-body">
      <h5 class="card-title">Services</h5>
      <p class="card-text">Free post for user <br> Grading option granted to User <br>Dashbord visual on Company portal</p>
    </div>
  </div>
  <div class="card">
    <%= image_tag('bene.png', class:"card-img-top") %>
    <div class="card-body">
      <h5 class="card-title">Beneficials </h5>
      <p class="card-text">This App can benefit both the Consumers, Company owner and the company itself. this App allows customers to leave a feedback . Feedback is beneficial to company for improvement of its products and services.</p>
    </div>
  </div>
</div>
</div>
</div>
</div><br>
<%= yield %>
</body>

</html>